apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-brfw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-brfw@sha256:cdb98034c156b4dd4a04532e9ff4845cafccd32b4c2ab57bf84fd9f88a326c96
        name: my-nodejs
        resources: {}
status: {}
